# Generated by Django 4.2 on 2023-08-28 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogspot',
            name='head0_content',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='blogspot',
            name='head1_content',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='blogspot',
            name='head2_content',
            field=models.CharField(default='', max_length=500),
        ),
    ]
